apiVersion: v1
kind: Service
metadata:
  name: time-app-metrics-exporter
  labels:
    app: time-app-metrics-exporter
spec:
  selector:
    app: time-app-metrics-exporter
  ports:
    - name: metrics
      port: 8088
      targetPort: 8000
      protocol: TCP
